version: '2'
services:
  api:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
      - kafka
    links:
      - db
      - redis
      - kafka
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  redis:
    image: redis
  kafka:
    image: jeqo/apache-kafka:0.10.1.0-2.11
    links:
      - zookeeper
  zookeeper:
    image: jeqo/apache-zookeeper:3.4.8